loki:
  domain: "root@loki.websages.com"
  deploy_to: "/var/cache/git/recollections"
  repository: "gitosis@freyr.websages.com:recollections.git"
  branch: "master"
  post_deploy_script: bin/setup
  post_setup_script:  bin/setup
